version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - "monitoring"
    volumes:
    # prometheus's DB files
      - 'prometheus_data:/prometheus'
    # конфигурационный файл с настройками prometheus
      - ./prometheus/conf:/etc/prometheus/
    command:
    # указываем параметры запуска с настройками из конф файла
      - '--config.file=/etc/prometheus/prometheus.yml'
    # храним метрики, дней (default 15d)
      - '--storage.tsdb.retention.time=7d'
  grafana:
    image: grafana/grafana-enterprise:main
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - "monitoring"
    volumes:
    # Grafana's DB files
      - 'grafana_data:/var/lib/grafana'
    #автоподключение источника данных prometheus, loki, установить в файлах свой IP!
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
  promtail:
    image: grafana/promtail:main-41eb82b
    container_name: promtail
    restart: unless-stopped
    ports:
      - "9080:9080"
    networks:
      - "monitoring"
    volumes:
    # копируем логи
      - '/home/usersamba/smb/logs:/var/log/prod'
      - '/home/usersamba/regres/Logs:/var/log/regres'
    # настройки конф файла
      - ./promtail/conf:/etc/promtail
    # настраиваем файл, хранящий позицию на которой остановилось чтение
      - ./promtail/positions:/tmp
    command:
      - '--config.file=/etc/promtail/promtail-local-config.yaml'
    #Режим отладки (--dry-run отключает передачу данных в loki)  
#      - '--inspect'
#      - '--dry-run'
  loki:
    image: grafana/loki:main-41eb82b
    container_name: grafana-loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    networks:
      - "monitoring"
    volumes:
    # loki's DB
      - 'loki_data:/loki'
      # настройки конф файла
      - ./loki/conf:/etc/loki
    command: 
      - '--config.file=/etc/loki/loki-local-config.yaml'
  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - "9091:9091"
    networks:
      - "monitoring"
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    #network_mode: host
    pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - "monitoring"
networks:
  monitoring:
    name: 'grafana'
volumes:
# Хранилище данных grafana
  grafana_data: {}
# Хранилище данных prometheus
  prometheus_data: {}
# Хранилище данных loki
  loki_data: {}
