apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    #host.docker.internal - good for windows OS
    #localhost
    url: http://loki:3100
    jsonData:
      maxLines: 1000
